# Generated by Django 4.2 on 2026-02-15 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, help_text='Name of the donor (optional)', max_length=100, null=True)),
                ('donor_email', models.EmailField(blank=True, help_text='Email address of the donor (optional)', max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount in currency (0.01 to 999,999.99)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999999.99)])),
                ('transaction_reference', models.CharField(db_index=True, editable=False, help_text='Unique transaction reference (auto-generated)', max_length=50, unique=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from the donor (max 500 characters)', max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when donation was created')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['transaction_reference'], name='Donations_d_transac_78bf90_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['-timestamp'], name='Donations_d_timesta_6b561a_idx'),
        ),
    ]
